# Generated by Django 6.0 on 2025-12-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='contact',
        ),
        migrations.AddField(
            model_name='container',
            name='vehicles',
            field=models.ManyToManyField(related_name='containers', to='kanban.vehicle'),
        ),
        migrations.AddField(
            model_name='container',
            name='whatsapp_sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='kanban.whatsappaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='contacts',
            field=models.ManyToManyField(related_name='vehicles', to='kanban.contact'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_car',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='whatsapp_accounts',
            field=models.ManyToManyField(related_name='vehicles', to='kanban.whatsappaccount'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
