# Generated by Django 6.0 on 2025-12-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_remove_container_vehicle_remove_vehicle_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='whatsapp_account',
        ),
    ]
