# Generated by Django 6.0 on 2025-12-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_remove_container_whatsapp_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='kanban.container')),
            ],
        ),
    ]
