# Generated by Django 6.0 on 2025-12-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='message_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_vehicles', to='kanban.contact'),
        ),
        migrations.AlterField(
            model_name='container',
            name='whatsapp_sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='kanban.whatsappaccount'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='whatsapp_accounts',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='kanban.whatsappaccount'),
        ),
    ]
