# Generated by Django 6.0 on 2025-12-22 11:19

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_links(apps, schema_editor):
    connection = schema_editor.connection
    table_names = connection.introspection.table_names()
    old_table = 'kanban_container_vehicles'
    if old_table not in table_names:
        return
    ContainerVehicle = apps.get_model('kanban', 'ContainerVehicle')
    with connection.cursor() as cursor:
        cursor.execute(f'SELECT container_id, vehicle_id FROM {old_table}')
        rows = cursor.fetchall()
    for container_id, vehicle_id in rows:
        ContainerVehicle.objects.create(container_id=container_id, vehicle_id=vehicle_id)


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_pipelinestage_message_template_vehicle_phone_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.container')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_vehicle_responsible', to='kanban.contact')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.vehicle')),
            ],
        ),
        migrations.RunPython(copy_existing_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='container',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='container',
            name='vehicles',
            field=models.ManyToManyField(related_name='containers', through='kanban.ContainerVehicle', to='kanban.vehicle'),
        ),
    ]
