# Generated by ChatGPT on 2025-12-22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_containervehicle_alter_container_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='message_template_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='message_template_kg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='container',
            name='arrival_time_bishkek',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='arrival_time_osh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='container',
            name='mute_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='mute_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='transit_erkishtam',
            field=models.BooleanField(default=False),
        ),
    ]
